# 체크리스트
# [x] 설정 -- /_config.yml
# [x] 도메인 -- /CNAME
# [x] 메뉴 구성 -- /_includes/nav.html
# [x] 첫 페이지 제목 -- /index.md
# [x] 아카이브 제목 -- /archives.md
# [x] 샘플 포스트 삭제 -- /_posts/2023-01-29-lorem-ipsum.md

# 빌드 타겟
exclude:
  - oxmhpark.code-workspace
  - _config.yml.sample
  - .gitattributes
  - .gitignore
  - .hintrc
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CNAME

# 운영자 정보
author: "옥수박"

# 웹사이트 정보
title: "NEMORIUM.NET"
description: ""
lang: "ko"
timezone: "Asia/Seoul"
stylesheet_url: "/assets/style.css"
favicon_url: "/assets/CIN_TIGHT@NEMORIUM.NET.png"

# 주소체계
url: "https://nemorium.net"
enforce_ssl: "https://nemorium.net"
baseurl: "/"
permalink: ":slug"
format:
  date: "%Y.%m.%d."
  year: "%Y"

# HTML/CSS 파서
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded

# 기본값
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
      meta:
        - address
        - author
        - date
        - lastmod
        - years
        - categories
        - tags
      read_more:
        label: "전문 읽기 &rarr;"
  -
    scope:
      path: "_entry_posts"
    values:
      layout: "post"
      meta:
        - address
        - date
        - lastmod
        - years
        - categories
        - tags
  -
    scope:
      path: "_entry_pages"
    values:
      layout: "page"
      meta:
        - address
        - date
        - lastmod
  -
    scope:
      path: "_entry_terms"
    values:
      layout: "page"
      meta:
        - address
        - date
        - lastmod
  -
    scope:
      path: "_entry_bookmarks"
    values:
      layout: "page"
      meta:
        - address
      read_more:
        label: "[메모]"
  -
    scope:
      path: "_archive_years"
    values:
      layout: "year"
      meta:
        - address
  -
    scope:
      path: "_archive_categories"
    values:
      layout: "category"
      meta:
        - address
  -
    scope:
      path: "_archive_tags"
    values:
      layout: "tag"
      meta:
        - address

# 추가 형식
collections:
  posts:
    output: false
    path: _posts
    permalink: ":slug"
    layout: post
  pages:
    output: false
    path: _pages
    permalink: ":slug"
    layout: page
  entry_posts:
    output: true
    path: _entry_posts
    permalink: ":slug"
    layout: post
  entry_pages:
    output: _entry_pages
    path: _entry_pages
    permalink: ":slug"
    layout: page
  entry_terms:
    output: _entry_terms
    path: _entry_terms
    permalink: ":slug"
    layout: page
  entry_bookmarks:
    output: _entry_bookmarks
    path: _entry_bookmarks
    permalink: ":slug"
    layout: page
  archive_years:
    output: true
    path: _archive_years
    permalink: "years/:slug"
    layout: year
  archive_categories:
    output: true
    path: _archive_categories
    permalink: "categories/:slug"
    layout: category
  archive_tags:
    output: true
    path: _archive_tags
    permalink: "tags/:slug"
    layout: tag

# 플러그인
#plugins:
#  - jekyll-sitemap
#  - jekyll-feed
#  - jekyll-seo-tag
