# 체크리스트
# [x] 설정 -- /_config.yml
# [x] 도메인 -- /CNAME
# [x] 메뉴 구성 -- /_includes/nav.html
# [x] 첫 페이지 제목 -- /index.md
# [x] 아카이브 제목 -- /archives.md
# [x] 샘플 포스트 삭제 -- /_posts/2023-01-29-lorem-ipsum.md

# 빌드 타겟
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CNAME

# 운영자 정보
author: "옥수박"

# 웹사이트 정보
title: "NEMORIUM.NET"
description: ""
lang: "ko"
timezone: "Asia/Seoul"
stylesheet_url: "/assets/style.css"
favicon_url: "/assets/CIN_TIGHT@NEMORIUM.NET.png"

# 주소체계
url: "https://nemorium.net"
enforce_ssl: "https://nemorium.net"
baseurl: "/"
permalink: "/:title"
format:
  date: "%Y.%m.%d."
  year: "%Y"
  read_more:
    label: "마저 읽기 &rarr;"
  view_archives:
    url: "/archives"
    label: "전체목록 보기 &rarr;"

# HTML/CSS 파서
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded

# 기본값
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
  -
    scope:
      path: "_pages"
    values:
      layout: "page"
  -
    scope:
      path: "_years"
    values:
      layout: "year"
  -
    scope:
      path: "_categories"
    values:
      layout: "category"
  -
    scope:
      path: "_tags"
    values:
      layout: "tag"

# 추가 형식
collections:
  pages:
    output: true
    path: _pages
    permalink: "/:title"
    layout: page
  archives_years:
    output: true
    path: _archives_years
    permalink: "/years/:title"
    layout: year
  archives_categories:
    output: true
    path: _archives_categories
    permalink: "/categories/:title"
    layout: category
  archives_tags:
    output: true
    path: _archives_tags
    permalink: "/tags/:title"
    layout: tag

# 플러그인
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
